// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mHlOZd2OBZd8mpChZ7d0lBNzu1g0XL4',
    appId: '1:820864240000:web:afb3e0ddc8956e31439965',
    messagingSenderId: '820864240000',
    projectId: 'thimar-c0a4a',
    authDomain: 'thimar-c0a4a.firebaseapp.com',
    storageBucket: 'thimar-c0a4a.appspot.com',
    measurementId: 'G-07XE89TBYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBazNtIXjT9lSsr9xfl5CP_p7aVAl51OhM',
    appId: '1:820864240000:android:fddf19e4fdedf9d2439965',
    messagingSenderId: '820864240000',
    projectId: 'thimar-c0a4a',
    storageBucket: 'thimar-c0a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5qDFxem2_nNG3Q8Q5Hh47IthnngdMCKY',
    appId: '1:820864240000:ios:4fd76a62804a607e439965',
    messagingSenderId: '820864240000',
    projectId: 'thimar-c0a4a',
    storageBucket: 'thimar-c0a4a.appspot.com',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5qDFxem2_nNG3Q8Q5Hh47IthnngdMCKY',
    appId: '1:820864240000:ios:bcb168778f65b23b439965',
    messagingSenderId: '820864240000',
    projectId: 'thimar-c0a4a',
    storageBucket: 'thimar-c0a4a.appspot.com',
    iosBundleId: 'com.example.thimar.RunnerTests',
  );
}
